development: &default
  adapter: postgresql
  encoding: unicode
  database: message_of_the_day_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: message_of_the_day_test
